notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'
urlpatterns = [
    # Index Page
    path('', views.index, name='index'),
    path('createTeam/', views.CreateTeam.as_view(), name='createTeam'),

    # Settings Page
    path('team/<slug:slug>/settings/', views.settingsView, name='settingsView'),
    path('searchUser/', views.searchUser, name='searchUser'),
    path('team/<slug:slug>/addFM/', views.addFM, name='addFM'),
    path('team/<slug:slug>/addPMember/', views.addPMember, name='addPMember'),
    path('team/<slug:slug>/settings/folder/<int:folderId>/', views.settingsFolder, name='settingsFolder'),
    path('team/<slug:slug>/addFNMember/', views.addFNMember, name='addFNMember'),

    # Layout
    path('team/<slug:slug>/', views.startupView, name='startupView'),
    path('team/<slug:slug>/note/<uuid:uuid>/', views.noteDetail, name='detail'),
    path('updateContent/<int:notebook_id>/', views.updateContent, name='updateContent'),
    path('team/<slug:slug>/addPFN/<int:oid>/', views.addPFN, name='addPFN'),
    path('renamePFN/', views.renamePFN, name='renamePFN'),
]

project50/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), # new
    path('users/', include('django.contrib.auth.urls')),
]

notes/models.py
import uuid
from django.db import models
from django.conf import settings
from users.models import MyUser
from encrypted_model_fields.fields import EncryptedCharField

# Startup Objects: User -> Startup
class Startup(models.Model):
    name = models.CharField(max_length=200)
    perma = models.CharField(max_length=20, unique=True)
    founder = models.ManyToManyField(MyUser, related_name='founder_startup_set')
    employee = models.ManyToManyField(MyUser, related_name='employee_startup_set')

    def __str__(self):
        return self.name

# Project Objects: Startup -> Project
class Project(models.Model):
    name = EncryptedCharField(max_length=200)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE, related_name='startup_project_set')
    creator = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='creator_project_set')
    employee = models.ManyToManyField(MyUser, related_name='employee_project_set')

    def __str__(self):
        return "%s" % (self.name)

# Folder Objects: Startup -> Project -> Folder
class Folder(models.Model):
    name = EncryptedCharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_folder_set')
    creator = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='creator_folder_set')
    employee = models.ManyToManyField(MyUser, related_name='employee_folder_set')

    def __str__(self):
        return "%s" % (self.name)

# Notebook Objects: Startup -> Project -> Folder -> Notebook
class Notebook(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    name = EncryptedCharField(max_length=200)
    content = EncryptedCharField(max_length=20000, null=True)
    folder = models.ForeignKey(Folder,on_delete=models.CASCADE, related_name='folder_notebook_set')
    creator = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='creator_notebook_set')
    employee = models.ManyToManyField(MyUser, related_name='employee_notebook_set')
    lastChange = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s %s %s" % (self.name, self.folder, self.creator)
        

notes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Startup


class TeamForm(ModelForm):
    name = forms.CharField(max_length=100, label="Team Name")
    perma = forms.SlugField(max_length=20, label="Team Perma-Link", help_text="It's your team's perma-link adress. e.g. 'Example Company' should be 'example-company' or 'example_company' or 'examplecompany'")
    class Meta:
        model = Startup
        fields = ['name', 'perma']

notes/views.py
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpRequest, JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from users.models import MyUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError

from .models import *
from .forms import TeamForm

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'notes/index.html', 
    {'startups': Startup.objects.filter(employee=request.user), 'founder': Startup.objects.filter(employee=request.user)})

class CreateTeam(LoginRequiredMixin, FormView):
    template_name = 'notes/createTeam.html'
    form_class = TeamForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        name = form.cleaned_data['name']
        perma = form.cleaned_data['perma']

        s = Startup(name=name, perma=perma)
        try:
            s.validate_unique()
        except:
            msg = u"Team with this Perma-Link already exists."
            form._errors["perma"] = form.error_class([msg])
            del form.cleaned_data["perma"]
            raise ValidationError(msg)
        s.save()
        s.employee.add(self.request.user)
        s.founder.add(self.request.user)
        return super().form_valid(form)

@login_required
def startupView(request, slug):
    return render(request, 'notes/notes.html', 
    {'startup': Startup.objects.filter(perma=slug)[:1], 'founder': Startup.objects.get(perma=slug, employee=request.user), 'allNotes': Notebook.objects.filter(employee=request.user)[:3]})

@login_required
def settingsView(request, slug):
    return render(request, 'notes/settings.html', 
    {'startup': Startup.objects.filter(perma=slug)[:1], 'founder': Startup.objects.get(perma=slug, employee=request.user), 'allNotes': Notebook.objects.filter(employee=request.user)[:3]})

@login_required
def noteDetail(request, uuid, slug):
    return render(request, 'notes/detail.html', 
    {'startup': Startup.objects.filter(perma=slug, employee=request.user)[0:1], 'founder': Startup.objects.filter(employee=request.user), 'notebook':Notebook.objects.get(uuid=uuid, employee=request.user), 'allNotes': Notebook.objects.filter(employee=request.user)[:3] })
        
@login_required
def updateContent(request, notebook_id):
    notebook = get_object_or_404(Notebook, pk=notebook_id)
    try:
        sn = Notebook.objects.get(pk=notebook_id)
        sn.content = request.POST['doc']
    except (KeyError, Notebook.DoesNotExist):
        return JsonResponse({'failed': 'There is no content here'})
    else:
        sn.save()
        return JsonResponse({'success': 'Content Updated'})

@login_required
def addPFN(request, oid, slug):
    if oid == 0:
        try:
            startup = Startup.objects.get(employee=request.user, perma=slug)
            name = request.POST['projectName']
            p = Project(name=name, startup=startup, creator=request.user)
        except (KeyError):
            return JsonResponse({'failed': 'There is no content here'})
        else:
            p.save()
            p.employee.add(request.user)
            return JsonResponse({'success': 'Project Add'})
    elif oid == 1:
        try:
            project = Project.objects.get(pk=request.POST['id'])
            f = Folder(name="New Folder", project=project, creator=request.user)
        except (KeyError, Project.DoesNotExist):
            return JsonResponse({'failed': 'There is no content here'})
        else:
            f.save()
            f.employee.add(request.user)
            return JsonResponse({'success': 'Folder Add'})
    elif oid == 2:
        try:
            folder = Folder.objects.get(pk=request.POST['id'])
            n = Notebook(name="New Note", folder=folder, creator=request.user)
        except (KeyError, Project.DoesNotExist):
            return JsonResponse({'failed': 'There is no content here'})
        else:
            n.save()
            n.employee.add(request.user)
            return JsonResponse({'uuid': n.uuid })

@login_required
def renamePFN(request):
    if request.POST['oid'] == "0":
        pfn = Project
    elif request.POST['oid'] == "1":
        pfn = Folder
    elif request.POST['oid'] == "2":
        pfn = Notebook
    else:
        return JsonResponse({'error': 'Something really wrong'})

    try:
        ipfn = int(request.POST["pfn"])
        p = pfn.objects.get(pk=ipfn)
        if request.user == p.creator:
            np = pfn.objects.get(pk=ipfn)
        else:
            return JsonResponse({'permissionError': 'Cannot do that'})
        if request.POST['did'] == "0":
            np.name=request.POST['newName']
        elif request.POST['did'] == "1":
            np.delete()
        else:
            return JsonResponse({'failed': 'Cannot do that'})
    except (KeyError, pfn.DoesNotExist):
        return JsonResponse({'failed': 'There is no content here'})
    else:
        np.save()
        if request.POST['did'] == "1":
            np.delete()
            np.save()
        return JsonResponse({'success': 'Project Renamed'})

# Settings Page
@login_required
def searchUser(request):
    try:
        userEmail = request.POST['email']
        u = MyUser.objects.get(email=userEmail)
    except (KeyError, MyUser.DoesNotExist):
        return JsonResponse({'failed': 'There is no user'})
    else:
        return JsonResponse({'success': 'User Found'})

@login_required
def addFM(request, slug):
    try:
        s = Startup.objects.get(founder=request.user, perma=slug)
        email = request.POST['userMail']
        u = MyUser.objects.get(email=email)
    except (KeyError, Startup.DoesNotExist):
        return JsonResponse({'failed': 1})
    else:
        if request.POST['oid'] == "0":
            s.founder.add(u)
            s.employee.add(u)
        elif request.POST['oid'] == "1":
            s.employee.add(u)
        elif request.POST['oid'] == "2":
            if request.user.email == request.POST['userMail']:
                return JsonResponse({'failed': 0})
            else:
                s.founder.remove(u)
        elif request.POST['oid'] == "3":
            if request.user.email == request.POST['userMail']:
                return JsonResponse({'failed': 0})
            else:
                s.employee.remove(u)
        s.save()
        return JsonResponse({'success': 'Founder/Member Add'})

@login_required
def addPMember(request, slug):
    try:
        s = Startup.objects.get(employee=request.user, perma=slug)
        try:
            Startup.objects.get(founder=request.user, perma=slug)
        except(KeyError, Startup.DoesNotExist):
            p = Project.objects.get(pk=request.POST['pid'], creator=request.user)
        else:
            p = Project.objects.get(pk=request.POST['pid'])
        email = request.POST['userMail']
        u = MyUser.objects.get(email=email)
    except (KeyError, Project.DoesNotExist):
        return JsonResponse({'failed': 'There is no content here'})
    else:
        if request.POST['oid'] == "0":
            p.employee.add(u)
        elif request.POST['oid'] == "1":
            if request.user.email == request.POST['userMail']:
                return JsonResponse({'failed': 0})
            else:
                p.employee.remove(u)
        p.save()
        return JsonResponse({'success': 'Something happened'})

@login_required
def settingsFolder(request, slug, folderId):
    return render(request, 'notes/settingsFolder.html', 
    {'startup': Startup.objects.filter(perma=slug)[:1], 'founder': Startup.objects.get(perma=slug, employee=request.user), 'allNotes': Notebook.objects.filter(employee=request.user)[:3], 'folder': Folder.objects.get(pk=folderId, employee=request.user)})

@login_required
def addFNMember(request, slug):
    if request.POST['oid'] == "0" or request.POST['oid'] == "2":
        fn = Folder
    elif request.POST['oid'] == "1" or request.POST['oid'] == "3":
        fn = Notebook
    try:
        m = fn.objects.get(pk=request.POST['fnid'], employee=request.user)
    except (KeyError, fn.DoesNotExist):
        return JsonResponse({'failed': 'There is no content here'})
    else:
        email = request.POST['userMail']
        u = MyUser.objects.get(email=email)
        if request.POST['oid'] == "2" or request.POST['oid'] == "3":
            if request.user.email == request.POST['userMail']:
                return JsonResponse({'failed': 0})
            else:
                m.employee.remove(u)
        elif request.POST['oid'] == "0" or request.POST['oid'] == "1":
            m.employee.add(u)
        m.save()
        return JsonResponse({'success': 'Something happened'})

templates/notes/createTeam.html
{% extends 'notes/layoutNoteless.html' %}
{% block SiteTitle %}Home{% endblock %}

{% block content %}
<h1>Create Team</h1>
<form action="/createTeam/" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
         <input type="text" name="{{ field.html_name }}" id="{{ field.html_name }}" class="form-control" aria-describedby="{{ field.id_for_label }}" placeholder="{{ field.placeholder }}">
         {% if field.help_text %}
        <small id="emailHelp" class="form-text text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}
 

templates/notes/detail.html
{% extends 'notes/layout.html' %}

{% block SiteTitle %}{{ notebook.name | truncatechars:17 }}{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a>{{ notebook.folder.project }}</a></li>
            <li class="breadcrumb-item"><a>{{ notebook.folder }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ notebook.name }}</li>
        </ol>
</nav>
{% endblock %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div id="scrolling-container">
        <div id="title"><h1>{{ notebook.name }}</h1></div>
        <div id="editor">Lorem ipsum dolor sit amet</div>
    </div>
{% endblock %}


{% block script %}
<script>
    var toolbarOptions = [
    ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
    ['blockquote', 'code-block'],
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
    [{ 'align': [] }],
    [{ 'color': [] }],
    ['clean']                                         // remove formatting button
    ];

    var quill = new Quill('#editor', {
    modules: {
        toolbar: toolbarOptions
    },
    theme: 'snow',
    
    placeholder: 'Compose an epic...'

    });

    var title = new Quill('#title', {
        modules: {
            toolbar: toolbarOptions
        },
        theme: 'bubble'
    });

    quill.root.spellcheck = false;
    title.root.spellcheck = false;

    texty = "{{ notebook.content|escapejs }}"
    if (texty != "None") {  
        textyjson = JSON.parse(texty);
        quill.setContents(textyjson);
    }
    

    var Delta = Quill.import('delta');
    
    var change0 = new Delta();
    title.on('text-change', function(delta) {
        change0 = change0.compose(delta);       
        $.ajax({
            'csrftoken': csrftoken,
            type:"POST",
            url:"/renamePFN/",
            data: {
                'did': "0",
                'oid': "2",
                'pfn': "{{ notebook.id }}",
                'newName': title.getText()
                }  
        });
        console.log("Title Changed")
        return false;
    });

    var change1 = new Delta();
    quill.on('text-change', function(delta) {
        change1 = change1.compose(delta);
        array = JSON.stringify(quill.getContents())
    });

    // Save periodically
    setInterval(function() {
    if (change1.length() > 0) {
        $.ajax({
            type:"POST",
            url:"/updateContent/{{ notebook.id }}/",
            data: {
                'doc': JSON.stringify(quill.getContents())
                },
            success: function(data){
                console.log("Changes Saved", data)
            }
        });
        return false;

        change1 = new Delta();
    }
    }, 5*1000);
    
    // Store accumulated changes

    title.formatLine(0, 1, 'align', 'center');

</script>
{% endblock %}

templates/notes/index.html
{% extends 'notes/layoutNoteless.html' %}

{% block SiteTitle %}Home{% endblock %}

{% block content %}
    {% if startups %}
        <div class="row">
        {% for startup in startups %}
            <div class="col-6 mb-4  ">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ startup.name }}</h5>
                        <p class="card-text">{{ startup.perma }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Founders <span class="badge badge-secondary">{{ startup.employee.count }}</span> :</strong>
                            {% for founder in startup.founder.all %} {{ founder.name }} {% endfor %}
                        </li>
                        <li class="list-group-item"><strong>Members <span class="badge badge-secondary">{{ startup.employee.count }}</span> :</strong>
                            {% for employee in startup.employee.all %} {{ employee.name }} {% endfor %}
                        </li>
                    </ul>
                    <div class="card-body">
                        <a href="/team/{{ startup.perma }}/" class="card-link">Team Link</a>
                        <a href="/team/{{ startup.perma }}/settings/" class="card-link">Team Settings</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <div class="jumbotron">
            <h1 class="display-4">Hello, {{ user.name }}!</h1>
            <p class="lead">We happy to see to you here. You are not in any Team. If you're a founder, create your team</p>
            <hr class="my-4">
            <p>If you're an employee or a customer, send your e-mail adress to the team. You can say "Hey get me in!"</p>
            <a class="btn btn-primary btn-lg" href="createTeam/" role="button">Create your team</a>
        </div>
    {% endif %}
{% endblock %}
 

templates/notes/layoutNoteless.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <!-- documentation at http://getbootstrap.com/docs/4.0/, alternative themes at https://bootswatch.com/4-alpha/ -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        
        <!-- Font Awesome-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

        <!-- Theme included stylesheets -->
        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
        <link href="https://cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}">

        <title>Noyte | {% block SiteTitle %}{% endblock %}</title>
    </head>

    <body>
        <div class="wrapper">
        <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <div class="row">
                        {% if user.is_authenticated %}
                            <div class="col-12">
                                <div class="profile-usertitle-startup pl-2 text-sidebar">
                                    {% for startup in startup %}{{ startup.name }}{% endfor %}
                                </div>
                            </div>
                            <div class="col-md-4 avatar">
                                    <img class="img-responsive" id="demo-image" src="https://api.adorable.io/avatars/75/{{ user.email }}" alt="avatar-image">
                            </div>
                            <div class="col-md-8 pb-4 pt-2">
                                <div class="profile-usertitle-name">
                                    {{ user.name }}
                                </div>
                                <div class="profile-usertitle-job">
                                    {% for startup in startup %}
                                        {% if request.user in startup.founder.all %}Founder{% else %}Employee{% endif %}
                                    {% endfor %}
                                </div>  
                            </div>
                        {% endif %}
                    </div>
                </div>
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-sidebar">
                    <span>Teams</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                            <i class="fas fa-plus-circle"></i>
                    </a>
                </h6>
                <ul class="list-unstyled components">
                    {% for startup in startups %}
                    <li>
                        <a id="{{ startup.perma }}" data-note-name="{{ startup.name }}" class="nav-link notebook-context" href="/team/{{ startup.perma }}/">
                            <i class="fas fa-users"></i> {{ startup.name }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                <a href="/createTeam/" class="btn btn-outline-info ml-2">Create New Team</a>
            </nav>
            

                        <!-- Page Content Holder -->
            <div id="content">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn navbar-btn btn-sidebar">
                                <i class="fas fa-bars"></i>
                            </button>
                        </div>
                        <div>
                            <ul class="nav justify-content-end">
                                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                            </ul>
                        </div>
                        
                    </div>
                </nav>
                {% block breadcrumb %}
                {% endblock %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <!-- AddProject Modal -->
        <div class="modal fade" id="addProject" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Add Project</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="addProjectForm" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                          <label for="projectName" class="col-form-label">Project Name:</label>
                          <input type="text" class="form-control" id="projectName" name="projectName">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="addProjectButton" type="submit" class="btn btn-primary" form="addProjectForm">Add New Project</button>
                </div>
                </div>
            </div>
        </div>

        <!-- Rename Modal -->
        <div class="modal fade" id="renamePFN" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="RenamePFNLabel">Rename: </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="renamePFNForm" method="post">
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="oid" name="oid">
                        <input type="hidden" class="form-control" id="pfn" name="pfn">
                        <label for="newName" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="newName" name="newName">
                    </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="renamePFNButton" type="button" class="btn btn-primary" form="renamePFNForm">Change</button>
                </div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

        <!-- Notify Js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>

        <!-- jQuery contextMenu -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.contextMenu.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.contextMenu.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.7.1/jquery.ui.position.js"></script>

        {% csrf_token %}
        <script type="text/javascript">
        // using jQuery
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        </script>
        
        <script>
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        // SideNav Initialization
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
            $('#sidebar, #content').toggleClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            $('[data-toggle="popover"]').popover()
            });
        });
        </script>

        {% block script %}
        {% endblock %}
    </body>
</html>

templates/notes/notes.html
{% extends 'notes/layout.html' %}

{% block SiteTitle %}Home{% endblock %}

{% block content %}
    {% if startup %}
        <div class="jumbotron">
            <h1 class="display-4">Hello, {{ user.name }}!</h1>
            <p class="lead"><strong>Useful information</strong>: Default behavior is the nobody can access your Projects but the members. </p>
            <h5>Necessary things to become a team member</h5>
            <hr class="my-4">
            <p>1-) Tell them to signup to Website</p>
            <p>2-) Add this new member to the Team with email adress in the Team Settings</p>
            <p>3-) Add this member to Project after whatever Folders and Notes that you want</p>
        </div>
    {% else %}
        <div class="jumbotron">
            <h1 class="display-4">Hello, {{ user.name }}!</h1>
            <p class="lead">We happy to see to you here. You are not in any Team. If you're a founder, create your team</p>
            <hr class="my-4">
            <p>If you're an employee or a customer, send your e-mail adress to the team. You can say "Hey get me in!"</p>
            <a class="btn btn-primary btn-lg" href="createTeam/" role="button">Create your team</a>
        </div>
    {% endif %}
{% endblock %}
 

templates/notes/results.html
<h1>{{ notebook.notebookTitle }}</h1>
{{ notebook.noteContent }}

<a href="{% url 'notes:detail' notebook.id %}">Back again?</a>